name: Deploy para paginas do GitHub

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: checa o repositorio
      uses: actions/checkout@v3
      
    - name: configura o GitHub Pages
      uses: actions/configure-pages@v3

    - name: cria os arquivos para deploy
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Publica no GitPages
